In [ ]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

PROJECT_DIR = Path.cwd().parent
print(PROJECT_DIR)
datapath = PROJECT_DIR / 'data' / 'raw' / 'stocks_panel_daily_qfq_baostock.csv'

df = pd.read_csv(datapath)
df["date"] = df["ticker"].astype(str).str.zfill(6)
df.head()

/Users/yimingma/Documents/Quant/a_share_multi_factor_project
<class 'pandas.DataFrame'>
RangeIndex: 642091 entries, 0 to 642090
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        642091 non-null  str
 1   ticker      642091 non-null  int64
 2   open        642091 non-null  float64
 3   high        642091 non-null  float64
 4   low         642091 non-null  float64
 5   close       642091 non-null  float64
 6   volume      642091 non-null  int64
 7   amount      642091 non-null  float64
 8   pct_change  642091 non-null  float64
 9   turnover    642091 non-null  float64
dtypes: float64(7), int64(2), str(1)
memory usage: 49.0 MB

Index(['date', 'ticker', 'open', 'high', 'low', 'close', 'volume', 'amount',
       'pct_change', 'turnover'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 642091 entries, 0 to 642090
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        642091 non-null  str
 1   ticker      642091 non-null  int64
 2   open        642091 non-null  float64
 3   high        642091 non-null  float64
 4   low         642091 non-null  float64
 5   close       642091 non-null  float64
 6   volume      642091 non-null  int64
 7   amount      642091 non-null  float64
 8   pct_change  642091 non-null  float64
 9   turnover    642091 non-null  float64
dtypes: float64(7), int64(2), str(1)
memory usage: 49.0 MB

In [11]:
df.columns

Index(['date', 'ticker', 'open', 'high', 'low', 'close', 'volume', 'amount',
       'pct_change', 'turnover'],
      dtype='str')

In [26]:
summary = (df.groupby("ticker")["date"].agg(["min", "max", "count"]).sort_values("count"))

print(summary)

           min     max  count
ticker
600930  600930  600930    115
1391    001391  001391    245
603296  603296  603296    583
688472  688472  688472    623
601059  601059  601059    691
...        ...     ...    ...
601607  601607  601607   2430
601601  601601  601601   2430
600085  600085  600085   2430
600031  600031  600031   2430
1       000001  000001   2430

[300 rows x 3 columns]

In [ ]:
min_obs = int(summary["count"].max() * 0.8)
valid_tickers = summary[summary["count"] >= min_obs].index.tolist()
df = df[df["ticker"].isin(valid_tickers)].copy()
print(f"number of valid stocks: {df['ticker'].nunique()}")

Number of valid tickers: 234
number of valid stocks: 234

In [ ]:
missing_ratio = df.isna().mean().sort_values(ascending=False)
missing_ratio

date          0.0
ticker        0.0
open          0.0
high          0.0
low           0.0
close         0.0
volume        0.0
amount        0.0
pct_change    0.0
turnover      0.0
dtype: float64

In [36]:
missing_ratio_byticker = df.groupby("ticker").apply(lambda x: x.isna().mean()).sort_values(by="date", ascending=False)
missing_ratio_byticker.head()

        date  open  high  low  close  volume  amount  pct_change  turnover
ticker
1        0.0   0.0   0.0  0.0    0.0     0.0     0.0         0.0       0.0
600803   0.0   0.0   0.0  0.0    0.0     0.0     0.0         0.0       0.0
600547   0.0   0.0   0.0  0.0    0.0     0.0     0.0         0.0       0.0
600570   0.0   0.0   0.0  0.0    0.0     0.0     0.0         0.0       0.0
600584   0.0   0.0   0.0  0.0    0.0     0.0     0.0         0.0       0.0

In [37]:
df[["open", "high", "low", "close", "volume", "amount", "turnover"]].describe()

,open,high,low,close,volume,amount,turnover
count,557521.000000,557521.000000,557521.000000,557521.000000,5.575210e+05,5.575210e+05,557521.000000
mean,29.067458,29.589910,28.605529,29.095469,4.929142e+07,8.400876e+08,1.200545
std,88.090202,89.244507,87.027479,88.125570,9.265678e+07,1.358260e+09,1.730519
min,1.031713,1.061474,1.031713,1.041634,5.000000e+02,1.842000e+04,0.002000
25%,6.589711,6.687779,6.500752,6.593248,1.037977e+07,1.955494e+08,0.349100
50%,13.597341,13.808749,13.406896,13.604809,2.380337e+07,4.185827e+08,0.681470
75%,27.063060,27.544285,26.638272,27.083966,5.323557e+07,9.307518e+08,1.349900
max,2268.442109,2303.415656,2178.177050,2279.854530,5.171253e+09,9.003765e+10,70.147134